---
abstract: "programmatic access to Google's Calendar API"
author:
  - 'Simon Wistow <simon@thegestalt.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-Calendar
provides:
  Net::Google::Calendar:
    file: lib/Net/Google/Calendar.pm
    version: 1.01
  Net::Google::Calendar::Base:
    file: lib/Net/Google/Calendar/Base.pm
    version: 0
  Net::Google::Calendar::Calendar:
    file: lib/Net/Google/Calendar/Calendar.pm
    version: 0
  Net::Google::Calendar::Comments:
    file: lib/Net/Google/Calendar/Comments.pm
    version: 0
  Net::Google::Calendar::Entry:
    file: lib/Net/Google/Calendar/Entry.pm
    version: 0
  Net::Google::Calendar::FeedLink:
    file: lib/Net/Google/Calendar/FeedLink.pm
    version: 0
  Net::Google::Calendar::Person:
    file: lib/Net/Google/Calendar/Person.pm
    version: 0
  Net::Google::Calendar::WebContent:
    file: lib/Net/Google/Calendar/WebContent.pm
    version: 0
requires:
  DateTime: 0
  LWP::UserAgent: 0
  Net::Google::AuthSub: 0
  Test::More: 0
  URI: 0
  URI::Escape: 0
  XML::Atom: 0.37
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
